### ISSUE TITLE
Remove ioncube_path from vars/main.yml

### ISSUE THREAD

**Issue by jardleex** [cristian04/ansible-ioncube#1]
Hello @cristian04,

please remove the variable `ioncube_path` from `vars/main.yml.` Otherwise it's quite hard to override the value. Defining it in `defaults/main.yml` is sufficient and make it way easier to override.
See [Ansible Variable Precedence](https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable)

Thank you

Jard

**Comment by cmarquezrusso** [comment]
Thank you for reporting the issue. It was fixed
